[package]
name = "selfscore_attack"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
om2m_access = { local = "../move" }

[addresses]
selfscore_attack = "0x0"
